name: Docker Image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      reason:
        description: "触发构建的原因"
        required: false
        default: "手动触发构建"

jobs:
  push_to_registries:
    name: 构建并推送Docker镜像
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 保存版本信息
        run: |
          git describe --tags > VERSION

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录GitHub容器注册表
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取元数据（标签、标签）
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ contains(github.ref, 'alpha') && 'deanxv/hixai2api-alpha' || 'deanxv/hixai2api' }}
            ${{ contains(github.ref, 'alpha') && format('ghcr.io/{0}-alpha', github.repository) || format('ghcr.io/{0}', github.repository) }}

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}